### ISSUE TITLE
kodlar

### ISSUE THREAD

**Issue by gorkemocmen** [AtaBaranta/Twitter_Direct_Message_Bot_Project#1]
tek bir main dosyası yerine bir kaç dosyaya bölsen daha derli toplu ve kullanışlı olur bence :)

**Comment by AtaBaranta** [comment]
> tek bir main dosyası yerine bir kaç dosyaya bölsen daha derli toplu ve kullanışlı olur bence :)

yorumun için teşekkür ederim. En kısa sürede güncellicem 👍 😄
